# Generated by Django 6.1 on 2026-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='feed_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
