# Generated by Django 6.1 on 2026-09-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingtype',
            options={'ordering': ['name'], 'verbose_name': 'Listing Type', 'verbose_name_plural': 'Listing Types'},
        ),
    ]
