# Generated by Django 6.1 on 2026-09-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_types', '0002_alter_listingtype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
