# Generated by Django 6.1 on 2026-09-04 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('conditions', '0002_alter_condition_options_alter_condition_slug'),
        ('currencies', '0001_initial'),
        ('listing_types', '0001_initial'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Listing Type',
                'verbose_name_plural': 'Listing Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='categories.category')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='conditions.condition')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='currencies.currency')),
                ('listing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listing_types.listingtype')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.location')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='listings_li_status_f5055b_idx'), models.Index(fields=['seller', '-created_at'], name='listings_li_seller__945c9a_idx'), models.Index(fields=['category', '-created_at'], name='listings_li_categor_f61a31_idx'), models.Index(fields=['location', '-created_at'], name='listings_li_locatio_a16318_idx')],
            },
        ),
    ]
