# Generated by Django 6.1 on 2026-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
