# Generated by Django 6.1 on 2026-09-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['name'], 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterField(
            model_name='condition',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
